AccessReview/ARapp/urls.py
from django.urls import path, include
from django.contrib import admin

from . import views

app_name = "ARapp"
urlpatterns = [
    # ex: /ARapp/
    #path("", views.home, name="index")
    path("index/", views.index, name="index"),
    path("users/", views.UsersListView.as_view(), name="all_users"),
    path("about/", views.about, name="about"),
    path("reviewList/", views.ReviewListListView.as_view(), name="reviewList"),
    path("systemAdmin/reviewListAdd/", views.ReviewListAdd, name="reviewListAdd"),
    path("systemAdmin/countries/", views.CountriesListView.as_view(), name="countries"),
    path("countryAdd/", views.CountryAddForm, name="countryAdd"),
    path("submit/reviewListAdd/", views.ReviewListSubmit, name="submit_reviewListAdd"),
    path("systems/", views.SystemsListView.as_view(), name="systems"),
    path("systems/<int:pk>", views.SystemDetailView.as_view(), name="system_detail"),
    path("systems/<int:pk>/countries/", views.CountryListView.as_view(), name="system_country_view"),
    path("temp_review/", views.temp_review, name="temp_rev")

    # path("systems/", views.systems, name="systems"),
    #path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    #path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    #path("<int:question_id>/vote/", views.vote, name="vote"),
]

AccessReview/AccessReview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('ARapp/', include('ARapp.urls')),
    path('', include('ARapp.urls')),
    path('admin/', admin.site.urls),
]

AccessReview/ARapp/models/model_Countries.py
from django.db import models
import django_tables2 as tables
from django import forms
import datetime




class Country(models.Model):
    countryName = models.CharField(max_length=255)
    isLive = models.BooleanField()
    
    def __str__(self):
        """Returns a string representation of a message."""
        return self.countryName
   


class CountryTable(tables.Table):
    class Meta:
        model = Country
        template_name = "django_tables2/bootstrap.html"
        fields = ("countryName", "isLive", )

    # Select = tables.TemplateColumn('''
    #                                 <a href="/systems/{{ record.id }}">Select</a> 
    #                                 <a href="/schedule/delete_schedule/{{ record.id }}" 
    #                                     onclick="return confirm('Are you sure you want to delete this?')">on click test</a>''')
    

class CountryAddForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = "__all__"
        # fields = ("countryName", "isLive")


#Table Countries{
#  id integer [primary key]
#  countryName varchar
#  isLive bool [note:'is the country still operational']
#}

AccessReview/ARapp/models/model_R_ReviewList.py
from django.db import models
import django_tables2 as tables
from django import forms
import datetime

from .model_Countries import Country
from .model_Systems import Systems



class R_ReviewList(models.Model):
    name = models.CharField(max_length=255)
#    system = models.CharField(max_length=255)  ##TODO change to system_ID and reference systemID from model_Systems.py
    system = models.ForeignKey(Systems, on_delete=models.PROTECT)       ##TODO think about cascade not protect  - https://stackoverflow.com/questions/38388423/what-does-on-delete-do-on-django-models
    country = models.ForeignKey(Country, on_delete=models.PROTECT)      ##TODO think about cascade not protect
    reviewRanBy = models.CharField(max_length=255, null=True) ##TODO change to employee_ID reference
    reviewStart = models.DateTimeField(null=True)
    reviewEnd = models.DateTimeField(null=True)     #this is when the review should end, do not confuse with reviewDone -> thats timestamp when  it actually finished
    allUsersDone = models.BooleanField(default=False)
    allUsersDoneTime = models.DateTimeField(null=True)  ##TODO decide to use DateField.auto_now or DateField.auto_now_add
    allManagersDone = models.BooleanField(default=False)
    allManagersDoneTime = models.DateTimeField(null=True)  ##TODO decide to use DateField.auto_now or DateField.auto_now_add
    assetOwnerDone = models.BooleanField(default=False)
    assetOwnerDoneTime = models.DateTimeField(null=True)  ##TODO decide to use DateField.auto_now or DateField.auto_now_add
    additionalActionsDone = models.CharField(max_length=255, null=True) ##TODO JIRA ticket for SD -> either link a table or just text
    additionalActionsDoneTime = models.DateTimeField(null=True)  ##TODO decide to use DateField.auto_now or DateField.auto_now_add
    reviewDone = models.BooleanField(default=False)
    reviewDoneTime = models.DateTimeField(null=True)  ##TODO decide to use DateField.auto_now or DateField.auto_now_add

    
    def __str__(self):
        """Returns a string representation of a review list."""
        return self.name
    

class ReviewListTable(tables.Table):
    class Meta:
        model = R_ReviewList
        template_name = "django_tables2/bootstrap.html"
        fields = ("name", "system", "country", )
    ##TODO modify to pull data based on selected system
    # Select = tables.TemplateColumn('''
    #                                 <a href="/systems/{{ record.id }}">Select</a> 
    #                                 <a href="/schedule/delete_schedule/{{ record.id }}" 
    #                                     onclick="return confirm('Are you sure you want to delete this?')">on click test</a>''')

class ReviewListForm(forms.ModelForm):
    class Meta:
        model = R_ReviewList
        # fields = "__all__"
        fields = ("name", "system", "country")

AccessReview/ARapp/models/model_R_ReviewOptions.py
from django.db import models
import datetime

class R_ReviewResponseOptions(models.Model):
    response = models.CharField(max_length=255)
    
    def __str__(self):
        """Returns a string representation of a message."""
        return self.response





# /*
# Table R_ReviewResponseOptions{
#   id integer [primary key]
#   response varchar

# }
# */

AccessReview/ARapp/models/model_R_ReviewType.py
from django.db import models

class R_ReviewType(models.Model):
    type = models.CharField(max_length=255)
    
    def __str__(self):
        """Returns a string representation of a message."""
        return self.type
    


# Table R_ReviewType{
#   id integer [primary key]
#   type varchar [note:'type of review - physical, AD review etc']
# }

AccessReview/ARapp/models/model_Systems.py
from django.db import models
import django_tables2 as tables
import datetime

from .model_Countries import Country

class Systems(models.Model):
    systemName = models.CharField(max_length=255)
    criticality = models.CharField(max_length=255)
    systemDescription = models.TextField(null=True)
    #country = models.CharField(max_length=255)
    country = models.ManyToManyField(Country)


    
    def __str__(self):
        """Returns a string representation of a system."""
        return self.systemName
    

class SystemsTable(tables.Table):
    class Meta:
        model = Systems
        template_name = "django_tables2/bootstrap.html"
        fields = ("systemName", "criticality", "country.countryName", )
    ##TODO modify to pull data based on selected system
    Select = tables.TemplateColumn('''
                                    <a href="/systems/{{ record.id }}">Select</a> 
                                    <a href="/schedule/delete_schedule/{{ record.id }}" 
                                        onclick="return confirm('Are you sure you want to delete this?')">on click test</a>''')




#Table Systems{
#  id integer [primary key]
#  systemName varchar
#  criticality varchar
#  accessMatrix_ID integer [ref: - AccessMatrixList.id]
#  country_ID integer [ref: > Countries.id]
#  lastReviewedOn timestamp
#  assetOwner_ID integer [ref: - Users.employee_ID]
#}

AccessReview/ARapp/models/model_UserStatus.py
from django.db import models
import datetime

class UserStatus(models.Model):
    status = models.CharField(max_length=255)
    userType = models.CharField(max_length=255)

AccessReview/ARapp/models/model_UserStatusType.py
from django.db import models
import datetime

class UserStatus(models.Model):
    status = models.CharField(max_length=255)

class UserType(models.Model):
    userType = models.CharField(max_length=255)

AccessReview/ARapp/models/model_Users.py
from django.db import models
import datetime
import django_tables2 as tables

from .model_UserStatusType import UserStatus, UserType


# Create your models here.
class Users(models.Model):
    employee_ID = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    userStatus = models.ForeignKey('UserStatus', on_delete=models.PROTECT, null=True)  #info from bambooHR leave/terminated/live      ##TODO remove null 
    userType = models.ForeignKey('UserType', on_delete=models.PROTECT, null=True)      #info if contractor/employee/system          ##TODO remove null 
#    middleName = models.CharField(max_length=255, blank=True)
#    surName = models.CharField(max_length=255)
#    mail = models.CharField(max_length=255)
#    jobTitle = models.CharField(max_length=255, blank=True)
#    officeLocation = models.CharField(max_length=255, blank=True)
#    managerEmployeeID = models.ForeignKey('self', on_delete=models.CASCADE)
#    isEnabled = models.BooleanField()
#    isAssetOwner = models.BooleanField()
#    lastLoginAD = models.DateTimeField(blank=True, default=datetime.datetime.now())
#    lastLoginAPP = models.DateTimeField(blank=True, default=datetime.datetime.now())

    def __str__(self):
        """Returns a string representation of a message."""
        return self.employee_ID
    

class UsersTable(tables.Table):
    class Meta:
        model = Users
        template_name = "django_tables2/bootstrap.html"
        fields = ("employee_ID", "name", "userStatus.status", "userType.userType", )

AccessReview/ARapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.urls import reverse
from django.views import generic

import django_tables2 as tables

from .models import Users, UsersTable
from .models import Systems, SystemsTable
from .models import Country, CountryTable, CountryAddForm
from .models import R_ReviewList, ReviewListTable, ReviewListForm
from .urls import *
# Create your views here.


def index(request):
    return render(request, "ARapp/index.html")

def about(request):
    return render(request, "ARapp/about.html")

def temp_review(request):
    if request.method == 'POST':
        post_coutryID= request.POST["countryID"]
        post_systemID = request.POST["systemID"]
        dict = {
            'country': request.POST["countryID"],
            'system': request.POST["systemID"]
        }
    return render(request, "ARapp/temp_review.html", dict)

def ReviewListAdd(request):
    context = {}
    context['add_new_review_form'] = ReviewListForm()
    return render(request, "ARapp/systemAdmin/reviewList_add.html", context)


def ReviewListSubmit(request):
    if request.method == 'POST':
        d = ReviewListForm(request.POST)
        d.save()
    return render(request, "ARapp/index.html")

def CountryAdd(request):
    context = {}
    context['add_new_coutry_form'] = CountryAddForm()
    return render(request, "ARapp/country_add.html", context)            

class UsersListView(tables.SingleTableView):
    model = Users
    table_class = UsersTable
    # queryset = Users.objects.all()
    context_object_name = "user_list"
    template_name = "ARapp/users.html"

class SystemsListView(tables.SingleTableView):
    model = Systems
    table_class = SystemsTable
    context_object_name = "all_systems"
    template_name = "ARapp/systems.html"

class CountriesListView(tables.SingleTableView):
    model = Country
    table_class = SystemsTable
    context_object_name = "all_countries"
    template_name = "ARapp/systemAdmin/countries.html"    
 

class ReviewListListView(tables.SingleTableView):
    model = R_ReviewList
    table_class = SystemsTable
    context_object_name = "reviewListList"
    template_name = "ARapp/reviewList.html"
    

class SystemDetailView(generic.DetailView):
    model = Systems
    context_object_name = "system"
    #by defualt uses template_name = "ARapp/Systems_detail.html"


class CountryListView(tables.SingleTableView):
    model = Country
    table_class = CountryTable
    context_object_name = "countries_for_system"
    template_name = "ARapp/systems_countries.html"

AccessReview/ARapp/templates/ARapp/Systems_detail.html
{% extends "ARapp/layout.html" %}
{% load django_tables2 %}


{% block title %}
    System's detail
{% endblock title %}


{% block body_content%}
<h2> System Name :  {{system.systemName}} </h2>  <br />
<br />

{{system.systemDescription}}

<br />
<br />
{% comment %} {% render_table system.country.all %} {% endcomment %}
{% if system.country.all %}
        <table class="country_list">
            <thead>
            <tr>
                <th>id</th>
                <th>name</th>
                <th>isLive</th>
                <th>Continue</th>
            </tr>
            </thead>
            <tbody>
            {% for country in system.country.all %}
                <tr>
                    <td>{{ country.id }}</td>
                    <td>{{ country.countryName }}</td>
                    <td>{{ country.isLive }}</td>
                    <td>
                        <form action="{% url 'ARapp:temp_rev' %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Select" />
                            {% comment %} <a href="{% url 'ARapp:temp_rev' %}">Select</a> {% endcomment %}
                            <input type="hidden" name="countryID" value={{ country.id }}>
                            <input type="hidden" name="systemID" value={{ system.id }}>
                        </form>
                    
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No systems have been logged.</p>
    {% endif %}
<br />

<a href="{% url 'ARapp:systems' %}">back to systems</a>

{% endblock body_content%}

AccessReview/ARapp/templates/ARapp/about.html
{% extends "ARapp/layout.html" %}

{% block title %}
    ABOUT 
{% endblock title %}


{% block body_content%}
<h2> ABOUT aa </h2>
{% endblock body_content%}






{% comment %} <!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>

<div class="container">
  <ul class="nav bg-info">
    <li class="nav-item">
      <a class="nav-link link-light" href="/ARapp">HOME</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="/ARapp/users">users</a>
    </li>
    <li class="nav-item">
        <a class="nav-link link-light" href="/ARapp/about">about</a>
      </li>
  </ul>

</div>



<h2>BLA BLA</h2>


</body>
</html> {% endcomment %}

AccessReview/ARapp/templates/ARapp/country_add.html
{% extends "ARapp/layout.html" %}
{% load django_tables2 %}


{% block title %}
    country ADD
{% endblock title %}


{% block body_content%}
    <form action="" method="post">
        {% csrf_token%}
        {{ add_new_coutry_form }}
        <input type="submit" value="Submit"> 
    </form> 

{% endblock body_content%}

AccessReview/ARapp/templates/ARapp/index.html
{% extends "ARapp/layout.html" %}

{% block title %}
<h2> INDEX </h2>
{% endblock title %}


{% block body_content%}
<h2> INDEX </h2>
{% endblock body_content%}







{% comment %} <!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>

    <div class="container">
        <ul class="nav bg-info">
          <li class="nav-item">
            <a class="nav-link link-light" href="/ARapp">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="/ARapp/users">users</a>
          </li>
          <li class="nav-item">
              <a class="nav-link link-light" href="/ARapp/about">about</a>
            </li>
        </ul>

    </div>

    <h2> INDEX </h2>

</body>
</html> {% endcomment %}

AccessReview/ARapp/templates/ARapp/layout.html
<!DOCTYPE html>
<html>
    <head>
        
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}


        <meta charset="utf-8"/>
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <div class="container">
            <ul class="nav bg-info">
                <li class="nav-item">
                    {% comment %} potrebuje url appName:name z urlpatters z urls.py {% endcomment %}
                    <a class="nav-link link-light" href="{% url 'ARapp:index' %}">INDEX</a>
                </li>
                <li class="nav-item">
                    {% comment %} <a class="nav-link link-light" href="/users">users</a> {% endcomment %}
                    <a class="nav-link link-light" href="{% url 'ARapp:all_users' %}">users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'ARapp:systems' %}">systems</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'ARapp:reviewList' %}">reviewList</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'ARapp:reviewListAdd' %}">reviewListADD</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'ARapp:countries' %}">countries</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'ARapp:about' %}">about</a>
                </li>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                      SystemAdmin
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                      <li><a class="dropdown-item" href="{% url 'ARapp:reviewListAdd' %}">reviewListADD</a></li>
                      <li><a class="dropdown-item" href="{% url 'ARapp:countries' %}">countries</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </div>
            </ul>
        </div>

    <body>
        {% block body_content %}{% endblock body_content %}
        <br />
        <br />
        <br />
        <br />
        
    </body>
    <footer>
        <p>&copy; 2024</p>
    </footer>

</html>

AccessReview/ARapp/templates/ARapp/reviewList.html
{% extends "ARapp/layout.html" %}
{% load django_tables2 %}


{% block title %}
    Review List 
{% endblock title %}


{% block body_content%}
    {% if reviewListList %}
            {% render_table reviewListList %}
    {% else %}
        <p>No review lists have been logged.</p>
    {% endif %}

{% endblock body_content%}

AccessReview/ARapp/templates/ARapp/systems.html
{% extends "ARapp/layout.html" %}
{% load django_tables2 %}


{% block title %}
    Systems 
{% endblock title %}


{% block body_content%}
    {% if all_systems %}
            {% render_table table %}
    {% else %}
        <p>No systems have been logged.</p>
    {% endif %}


    {% comment %} <h2>System list</h2>

    {% if all_systems %}
        <table class="system_list">
            <thead>
            <tr>
                <th>name</th>
                <th>crit</th>
                <th>country</th>
            </tr>
            </thead>
            <tbody>
            {% for system in all_systems %}
                <tr>
                    <td>{{ system.systemName }}</td>
                    <td>{{ system.criticality }}</td>
                    <td>{{ system.country.countryName }}</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No systems have been logged.</p>
    {% endif %} {% endcomment %}

{% endblock body_content%}

AccessReview/ARapp/templates/ARapp/temp_review.html
{% extends "ARapp/layout.html" %}

{% block title %}
TEMP REVIEW SITE - review <br />
{% endblock title %}

{% block body_content%}
<p>Country is :{{country}}</p>
<p>System is: {{system}}</p>
{% endblock body_content%}

AccessReview/ARapp/templates/ARapp/temp_reviewList_add.html
{% extends "ARapp/layout.html" %}
{% load django_tables2 %}


{% block title %}
    Temp Review List ADD
{% endblock title %}


{% block body_content%}
    <form action="{% url 'ARapp:submit_reviewListAdd'%}" method="post">
        {% csrf_token%}
        {{ add_new_review_form }}
        <input type="submit" value="Submit"> 
    </form> 

{% endblock body_content%}

AccessReview/ARapp/templates/ARapp/users.html
{% extends "ARapp/layout.html" %}
{% load django_tables2 %}

{% block title %}
    Users 
{% endblock title %}


{% block body_content%}
    <h2>User list</h2>

    {% if user_list %}
        {% render_table table %}
    {% else %}
        <p>No users have been logged.</p>
    {% endif %}

{% endblock body_content%}

{% comment %} 
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>

    <div class="container">
        <ul class="nav bg-info">
          <li class="nav-item">
            <a class="nav-link link-light" href="/ARapp">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="/ARapp/users">users</a>
          </li>
          <li class="nav-item">
              <a class="nav-link link-light" href="/ARapp/about">about</a>
            </li>
        </ul>
    </div>


{% block content2 %}
<h2>User list</h2>

{% if user_list %}
    <table class="message_list">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>status</th>
            <th>user type</th>
        </tr>
        </thead>
        <tbody>
        {% for user in user_list %}
            <tr>
                <td>{{ user.employee_ID }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.userStatus.status }}</td>
                <td>{{ user.userType.userType }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No users have been logged.</p>
{% endif %}
{% endblock %}



</body>
</html> {% endcomment %}